### ISSUE TITLE
Docker環境構築

### ISSUE THREAD

**Issue by NKotani** [NKotani/AE2Team2#1]
Vuetify2+Go+MySQL

- [x] Docker Desktopの追加

### platform問題
```bash
failed to solve: mysql:5.7: no match for platform in manifest sha256:2c23f254c6b9444ecda9ba36051a9800e8934a2f5828ecc8730531db8142af83: not found
```
[platform解決](https://qiita.com/ktnyt/items/cefcb424a75f536f8422)

### apt-get問題
```bash
 > [db 2/3] RUN apt-get update && apt-get install -y --no-install-recommends     vim:
0.153 /bin/sh: apt-get: command not found
```
[apt-get解決](https://stackoverflow.com/questions/76292874/dockerfile-on-mac-studio-with-m1-chip-cant-run-apt-get-commands)

### sql-migrate問題
次のコマンドが失敗する
```bash
RUN go get -v github.com/rubenv/sql-migrate/...
```
M1 MacではなくGoのバージョンの問題でした
`60.41 note: module requires Go 1.17`

### FROM mysql:8.0-debianにしたときの問題
docker/mysql/Dockerfile
```bash
 => ERROR [db 3/3] RUN touch /var/log/mysql/mysqld.log                     0.3s
------
 > [db 3/3] RUN touch /var/log/mysql/mysqld.log:
0.295 touch: cannot touch '/var/log/mysql/mysqld.log': No such file or directory
------
failed to solve: process "/bin/sh -c touch /var/log/mysql/mysqld.log" did not complete successfully: exit code: 1
```

[Dockerfileに追記で解決](https://blueskyarea.hatenablog.com/entry/2019/12/02/220749)

## version
docker/front/DockerfileでFROM node:18.17.1-alpineにした
```bash
704.2 npm WARN notsup Unsupported engine for npm@10.0.0: wanted: {"node":"^18.17.0 || >=20.5.0"} (current: {"node":"14.17.0","npm":"6.14.13"})
704.2 npm WARN notsup Not compatible with your version of node/npm: npm@10.0.0
704.2 
704.2 + npm@10.0.0
704.2 added 122 packages from 50 contributors, removed 293 packages and updated 142 packages in 19.531s
704.3 /usr/local/lib/node_modules/npm/lib/es6/validate-engines.js:31
704.3     throw err
704.3     ^
```
nodeに`-alpine`をつけないとapkがnot foundになる
```bash
/bin/sh: 1: apk: not found
```

## apk問題
```bash
------
 > [front 3/3] RUN apk update &&     apk add python make g++ &&     npm install -g npm &&     npm install -g vue-cli:
0.094 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
1.741 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
4.270 v3.18.3-144-ga1c09996b47 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
4.270 v3.18.3-143-gb6caa842e6b [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
4.270 OK: 19938 distinct packages available
4.406 ERROR: unable to select packages:
4.406   python (no such package):
4.406     required by: world[python]
------
failed to solve: process "/bin/sh -c apk update &&     apk add python make g++ &&     npm install -g npm &&     npm install -g vue-cli" did not complete successfully: exit code: 1
```
[docker/front/Dockerfileでpython3を指定すると解決](https://stackoverflow.com/questions/62169568/docker-alpine-linux-python-missing)

## フロントのサーバーとDB問題
`bash scripts/start-front.sh`
```bash
    at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
10% building 2/5 modules 3 active ...tp://172.23.0.3:8080&sockPath=/sockjs-nodenode:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:471:10)
    at /app/node_modules/webpack/lib/NormalModule.js:503:5
    at /app/node_modules/webpack/lib/NormalModule.js:358:12
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /app/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1

```
[package-lock.jsonをアップデートする](https://zenn.dev/niccari/articles/ffdd621eb6be5a)
`docker-compose exec front npm audit fix --force` した
```bash
 ERROR  ValidationError: Progress Plugin Invalid Options
        
        options should NOT have additional properties
        options should NOT have additional properties
        options should NOT have additional properties
        options should pass "instanceof" keyword validation
        options should match exactly one schema in oneOf
```
[解決せず](https://qiita.com/Trae/items/785243619216750c98fc)

#### npm version 問題
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @vue/cli-plugin-eslint@5.0.8
npm ERR! Found: eslint@5.16.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^5.16.0" from the root project
npm ERR!   peer eslint@">= 4.12.1" from babel-eslint@10.1.0
npm ERR!   node_modules/babel-eslint
npm ERR!     dev babel-eslint@"^10.1.0" from the root project
npm ERR!   4 more (eslint-config-airbnb-base, eslint-plugin-import, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=7.5.0" from @vue/cli-plugin-eslint@5.0.8
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^5.0.8" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.48.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@">=7.5.0" from @vue/cli-plugin-eslint@5.0.8
npm ERR!   node_modules/@vue/cli-plugin-eslint
npm ERR!     dev @vue/cli-plugin-eslint@"^5.0.8" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-09-05T08_18_47_992Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-05T08_18_47_992Z-debug-0.log
```
→yukkxiさんとバージョンを揃えて解決済み

## webpack問題
```bash
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
nodeのバージョンは18以上から変更不可
[ENVをdocker/front/Dockerfileに設定して解決](https://vamdemicsystem.black/vue/%E3%80%90vue%E3%80%91vue%E3%81%A7%E3%83%9E%E3%83%AB%E3%83%81%E3%82%B9%E3%83%86%E3%83%BC%E3%82%B8%E3%83%93%E3%83%AB%E3%83%89%E3%81%AEdockerfile%E3%81%AE%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB)

**Comment by NKotani** [comment]
<img width="924" alt="スクリーンショット 2023-09-05 9 24 34" src="https://github.com/NKotani/AE2Team2/assets/82433118/e0cb58f3-d83f-44b5-8e02-32fb51bef29b">
画像載せられるのでフロントの見た目をスクショして貼る

**Comment by NKotani** [comment]
<img width="1149" alt="スクリーンショット 2023-09-06 11 16 16" src="https://github.com/NKotani/AE2Team2/assets/82433118/75faf6b3-eb16-4f46-a28b-48de03451aff">
エラーまだまだたくさんあるけど、とりあえず立ち上がるのでOK
